# Generated by Django 4.2.1 on 2023-05-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Фракция/группировка')),
            ],
        ),
        migrations.CreateModel(
            name='Duelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Исход дуэли')),
                ('duelist1', models.ManyToManyField(related_name='duelist1', to='main.duelist', verbose_name='Дуэлянт №1')),
                ('duelist2', models.ManyToManyField(related_name='duelist2', to='main.duelist', verbose_name='Дуэлянт №2')),
            ],
        ),
    ]
