# Generated by Django 4.2.1 on 2023-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='duelist1',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='duelist2',
        ),
        migrations.AddField(
            model_name='duel',
            name='duelist1',
            field=models.TextField(blank=True, max_length=50, verbose_name='Дуэлянт №1'),
        ),
        migrations.AddField(
            model_name='duel',
            name='duelist2',
            field=models.TextField(blank=True, max_length=50, verbose_name='Дуэлянт №2'),
        ),
    ]
